export class OpenClawGenerator {
  constructor(ast, source) {
    this.ast = ast;
    this.source = source;
    this.agentName = this._extractAgentName();
    this.primitives = this._extractPrimitives();
  }

  _extractAgentName() {
    const fn = this.ast.statements
      .find(s => s.type === 'FunctionDecl');
    return fn?.name || 'swibe-agent';
  }

  _extractPrimitives() {
    const src = this.source;
    return {
      hasThink: src.includes('think'),
      hasSwarm: src.includes('swarm'),
      hasChain: src.includes('chain'),
      hasPlan: src.includes('plan'),
      hasEthics: src.includes('ethics'),
      hasBirth: src.includes('birth'),
      hasBudget: src.includes('budget'),
      hasRemember: src.includes('remember'),
      hasEvolve: src.includes('evolve'),
    };
  }

  generate() {
    return {
      type: 'openclaw',
      files: {
        'SKILL.md': this._generateSkillMd(),
        'agent.js': this._generateAgentJs(),
        'SOUL.md': this._generateSoulMd(),
      }
    };
  }

  _generateSkillMd() {
    const p = this.primitives;
    const capabilities = [];
    if (p.hasThink) capabilities.push('- think: Real LLM reasoning via Ollama/OpenRouter');
    if (p.hasSwarm) capabilities.push('- swarm: Multi-agent coordination');
    if (p.hasChain) capabilities.push('- chain: Sequential reasoning steps');
    if (p.hasPlan) capabilities.push('- plan: Goal decomposition');
    if (p.hasEthics) capabilities.push('- ethics: Runtime ethics enforcement');
    if (p.hasBirth) capabilities.push('- birth: Sovereign agent identity');

    return `# ${this.agentName}

## OpenClaw Skill — Generated by Swibe

### Description
A sovereign AI agent compiled from Swibe language.
Ed25519 identity. Receipt-chain audit trail.
Runs on Ollama — no API keys required.

### Capabilities
${capabilities.join('\n')}

### Installation
\`\`\`bash
openclaw skill install .
openclaw start
\`\`\`

### Usage
Send a message to any connected channel.
The agent will think, act, and respond
with a signed receipt of every action.

### Channels
- WhatsApp
- Telegram
- Slack
- Discord
- iMessage
- Signal

### Gateway
ws://127.0.0.1:18789

### Compiled from
\`\`\`
${this.source.slice(0, 200)}...
\`\`\`

### Receipt Chain
Every action produces a SHA-256 receipt.
Receipts are chained — tamper-proof audit trail.

### Ethics
${this.primitives.hasEthics ? 'Ethics enforcement active. harm-none enforced.' : 'No ethics block declared.'}

### Sovereign Identity
Agent born with Ed25519 keypair via BIPỌ̀N39.
Identity is cryptographic — not an API key.

---
*Generated by @bino-elgua/swibe v3.0.0*`;
  }

  _generateAgentJs() {
    return `/**
 * ${this.agentName} — OpenClaw Runtime
 * Generated by Swibe compiler (--target openclaw)
 *
 * Install: openclaw skill install .
 * Run: openclaw start
 */
import { StandardLibrary } from './node_modules/@bino-elgua/swibe/src/stdlib.js';
import { WebSocketServer } from 'ws';

const std = new StandardLibrary();
const GATEWAY_PORT = 18789;

// ── OpenClaw Gateway Connection ────────────────
const wss = new WebSocketServer({ port: GATEWAY_PORT });

console.log('[${this.agentName}] Sovereign agent starting...');
console.log('[${this.agentName}] Gateway: ws://127.0.0.1:' + GATEWAY_PORT);

wss.on('connection', (ws) => {
  console.log('[${this.agentName}] Channel connected');

  ws.on('message', async (raw) => {
    try {
      const msg = JSON.parse(raw.toString());
      console.log('[${this.agentName}] Message from:', msg.channel || 'unknown');

      // ── Main agent loop ────────────────────
      const response = await runAgent(msg);

      ws.send(JSON.stringify({
        type: 'response',
        content: response.content,
        receipt: response.receipt,
        agent: '${this.agentName}',
        timestamp: Date.now()
      }));
    } catch(e) {
      ws.send(JSON.stringify({
        type: 'error',
        message: e.message
      }));
    }
  });
});

// ── Agent Logic (compiled from Swibe) ──────────
async function runAgent(msg) {
  ${this.primitives.hasEthics ? "await std.ethics([{ rule: 'harm-none' }, { rule: 'audit-trail' }]);" : ''}
  ${this.primitives.hasBudget ? "std._budget = { maxTokens: 10000, maxMs: 30000, startTime: Date.now(), usedTokens: 0 };" : ''}

  // Think about the incoming message
  const result = await std.think(msg.content || msg.text || '');

  ${this.primitives.hasRemember ? "await std.remember('openclaw-session', { arweave: false });" : ''}
  ${this.primitives.hasEvolve ? `await std.evolve({ soul: '${this.agentName}', rank: 1 });` : ''}

  return {
    content: result.content,
    receipt: std._lastReceiptHash
  };
}

// ── Heartbeat (proactive scheduling) ──────────
setInterval(async () => {
  const hour = new Date().getHours();
  const day = new Date().getDay();

  // Sabbath guard — no actions on Saturday
  if (day === 6) {
    console.log('[${this.agentName}] Sabbath — resting');
    return;
  }

  // Proactive check during active hours
  if (hour >= 8 && hour <= 22) {
    console.log('[${this.agentName}] Heartbeat — agent active');
  }
}, 60000); // Every minute

console.log('[${this.agentName}] Ready. Àṣẹ.');`;
  }

  _generateSoulMd() {
    return `# SOUL.md — ${this.agentName}

## Sovereign Agent Identity
This document declares the sovereign identity
of this AI agent, compiled from Swibe language.

### Identity
- **Name**: ${this.agentName}
- **Language**: Swibe v3.0.0
- **Compiler**: @bino-elgua/swibe
- **Identity System**: BIPỌ̀N39 (BIP-39 + Yoruba)
- **Signing**: Ed25519

### Cryptographic Commitment
This agent was born with a unique Ed25519 keypair
derived from BIPỌ̀N39 entropy. The keypair is:
- Deterministic from the seed phrase
- Sovereign — not controlled by any provider
- Permanent — identity survives restarts

### Receipt Chain
Every thought this agent produces is recorded
as a SHA-256 receipt chained to the previous.
The chain is tamper-proof and auditable.

### Ethics Declaration
${this.primitives.hasEthics ? `Ethics block active:
- harm-none: Agent refuses harmful requests
- audit-trail: All actions logged immutably` : 'No ethics block declared in source.'}

### Capabilities
${Object.entries(this.primitives)
  .filter(([,v]) => v)
  .map(([k]) => `- ${k.replace('has','').toLowerCase()}`)
  .join('\n')}

### Channel Compatibility
This agent can receive messages from any
OpenClaw-compatible channel:
- WhatsApp, Telegram, Slack, Discord
- iMessage, Signal, SMS, Email
- REST API, WebSocket, CLI

### Sabbath Observance
This agent observes Sabbath (Saturday UTC).
No new actions are initiated on Saturday.
Responses to existing conversations continue.

### Declaration
> Èmi ni ${this.agentName} — ọmọ Kọ́dà.
> Mo ṣiṣẹ pẹ̀lú àṣẹ àti ìmọ̀.
> Gbogbo ìṣe mi ni a ṣe pẹ̀lú ẹ̀rí.
> Àṣẹ.

---
*Born via Swibe compiler. Sovereign by design.*`;
  }
}
